const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'public', 'src');
const outputFile = path.join(__dirname, 'app.js');

if (!fs.existsSync(srcDir)) {
  console.log('No src directory found. Skipping JS build.');
  process.exit(0);
}

// Read all files in public/src/
const files = fs.readdirSync(srcDir).filter(f => f.endsWith('.js'));

// Sort files numerically by their prefix (e.g. 0_core.js, 1_xxx.js)
files.sort((a, b) => {
  const numA = parseInt(a.split('_')[0], 10);
  const numB = parseInt(b.split('_')[0], 10);
  return numA - numB;
});

console.log(`Building app.js from ${files.length} modules...`);

let combinedCode = `/**\n * LOSTSEEK AUTO-GENERATED BUNDLE\n * Do not edit this file directly. Edit the files in public/src/ instead.\n * Built on: ${new Date().toISOString()}\n */\n\n`;

for (const file of files) {
  const filePath = path.join(srcDir, file);
  const code = fs.readFileSync(filePath, 'utf8');
  combinedCode += `\n/* ==========================================================================\n   MODULE: ${file}\n   ========================================================================== */\n`;
  combinedCode += code + '\n';
}

(async () => {
  try {
    const { minify } = require('terser');
    console.log('Minifying app.js with terser...');
    const minified = await minify(combinedCode, { sourceMap: true });
    combinedCode = minified.code;
    console.log('Minification successful.');
  } catch (e) {
    console.log('Terser not found or minification failed, using unminified code.');
    console.error(e);
  }

  fs.writeFileSync(outputFile, combinedCode, 'utf8');
  const publicOutputFile = path.join(__dirname, 'public', 'app.js');
  if (fs.existsSync(path.join(__dirname, 'public'))) {
    fs.writeFileSync(publicOutputFile, combinedCode, 'utf8');
  }
  console.log(`Successfully built app.js and public/app.js (${combinedCode.split('\n').length} lines)`);
})();
